import "./about.scss"

export default function About () {

    return <section id="about">
        <h1>ABOUT US</h1>
        <article>
            <h2>Heading 1 depicting motivations of the company</h2>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Unde impedit, suscipit ut quidem ipsam fuga quisquam optio mollitia nesciunt necessitatibus, praesentium quasi! Enim pariatur, nesciunt iste quos corrupti est optio quisquam placeat, accusantium nobis animi sapiente officia ipsa autem sit cum illum. Optio recusandae qui natus a. Quasi quibusdam esse corporis facere culpa iste ad quaerat ratione laudantium pariatur, asperiores, nam perferendis rerum sunt minima sequi recusandae. Fugit perspiciatis ex repellat reiciendis tempore aspernatur aperiam, dicta dolore iure magnam aut nesciunt libero? Itaque praesentium consequuntur tempore quidem eos. Eveniet ab dolor ipsum, ad magni, libero perferendis temporibus maiores reprehenderit sequi hic porro dolorum amet itaque optio praesentium ipsa earum officia adipisci eum eaque. Eligendi cum dolor incidunt ea illo soluta deserunt dicta minima modi sequi unde enim cupiditate a dolores necessitatibus molestiae aut iusto rem id quam saepe, aliquam veniam pariatur quia! Repellat eius vitae dignissimos tenetur repellendus iste corporis hic quasi temporibus veritatis dolores quod accusantium voluptates, nisi, ut ex quaerat beatae. Ad sapiente ipsam maiores nihil, veniam esse ipsum, fugiat, incidunt aspernatur id modi. Odit animi voluptates, est corrupti reprehenderit non tenetur eaque numquam nemo quam totam iure adipisci necessitatibus cupiditate natus, nostrum iste consequuntur autem magni fugit deleniti? Inventore dolorum sapiente distinctio asperiores rem quis veniam nesciunt vel aspernatur doloremque nobis itaque ut ipsa, qui aperiam. Unde nulla molestias corrupti!</p>
        </article>
        <article>
            <h2>Header 2 to show your professionalism and sell yours skills/product</h2>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Unde impedit, suscipit ut quidem ipsam fuga quisquam optio mollitia nesciunt necessitatibus, praesentium quasi! Enim pariatur, nesciunt iste quos corrupti est optio quisquam placeat, accusantium nobis animi sapiente officia ipsa autem sit cum illum. Optio recusandae qui natus a. Quasi quibusdam esse corporis facere culpa iste ad quaerat ratione laudantium pariatur, asperiores, nam perferendis rerum sunt minima sequi recusandae. Fugit perspiciatis ex repellat reiciendis tempore aspernatur aperiam, dicta dolore iure magnam aut nesciunt libero? Itaque praesentium consequuntur tempore quidem eos. Eveniet ab dolor ipsum, ad magni, libero perferendis temporibus maiores reprehenderit sequi hic porro dolorum amet itaque optio praesentium ipsa earum officia adipisci eum eaque. Eligendi cum dolor incidunt ea illo soluta deserunt dicta minima modi sequi unde enim cupiditate a dolores necessitatibus molestiae aut iusto rem id quam saepe, aliquam veniam pariatur quia! Repellat eius vitae dignissimos tenetur repellendus iste corporis hic quasi temporibus veritatis dolores quod accusantium voluptates, nisi, ut ex quaerat beatae. Ad sapiente ipsam maiores nihil, veniam esse ipsum, fugiat, incidunt aspernatur id modi. Odit animi voluptates, est corrupti reprehenderit non tenetur eaque numquam nemo quam totam iure adipisci necessitatibus cupiditate natus, nostrum iste consequuntur autem magni fugit deleniti? Inventore dolorum sapiente distinctio asperiores rem quis veniam nesciunt vel aspernatur doloremque nobis itaque ut ipsa, qui aperiam. Unde nulla molestias corrupti!</p>
        </article>
    </section>
}